apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: techtrends-app
  name: techtrends-app
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      k8s-app: techtrends-app
  template:
    metadata:
      labels:
        k8s-app: techtrends-app
    spec:
      containers:
        - image: {{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: techtrends-app
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu}}
              memory: {{ .Values.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.containerPort }}
          ports:
            - containerPort: {{ .Values.containerPort }}

