apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: techtrends-app
  name: techtrends-app
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      k8s-app: techtrends-app
  template:
    metadata:
      labels:
        k8s-app: techtrends-app
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.repository }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: techtrends-app
          resources:
            requests: {{ .Values.resources.requests }}
            limits: {{ .Values.resources.limits }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: 3111
          ports:
            - containerPort: 3111

