apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: techtrends-app
  name: techtrends-app
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    k8s-app: techtrends-app
  type: {{ .Values.service.type }}